In [4]:
import numpy as np
import torch

QUESTION 1

In [5]:
a= np.array([[0,1,2],[3,4,5],[6,7,8]])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
b = np.array([-1,1,-2])
b

array([-1,  1, -2])

In [7]:
np.dot(a,b)

array([ -3,  -9, -15])

In [8]:
a_pt = torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
a_pt

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
b_pt = torch.tensor([-1,1,-2])
b_pt

In [10]:
torch.matmul(a_pt, b_pt)

tensor([ -3,  -9, -15])

QUESTION 2

In [11]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
B= np.array([[1,0,0],[0,1,0],[0,0,1]])
B

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
np.dot(a,B)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
a_pt

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [17]:
B_pt = torch.tensor([[1,0,0],[0,1,0],[0,0,1]])
B_pt

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [18]:
torch.matmul(a_pt, B_pt)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

QUESTION 3

In [19]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
b2 = np.array([[-1,0],[1,1],[-2,2]])
b2

array([[-1,  0],
       [ 1,  1],
       [-2,  2]])

In [21]:
np.dot(a, b2)

array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])

In [22]:
a_pt

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [23]:
b_pt = torch.tensor([[-1,0],[1,1],[-2,2]])
b_pt

tensor([[-1,  0],
        [ 1,  1],
        [-2,  2]])

In [24]:
torch.matmul(a_pt, b_pt)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])