MATRIX INVERSION

In [1]:
import numpy as np

In [2]:
x= np.array([[4,2],[-5,-3]])
x

array([[ 4,  2],
       [-5, -3]])

In [3]:
x_inv = np.linalg.inv(x)
x_inv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [4]:
y = np.array([4,-7])
y

array([ 4, -7])

In [5]:
w = np.dot(x_inv , y)
w

array([-1.,  4.])

SHOW THAT y = xw

In [6]:
np.dot(x,w)

array([ 4., -7.])

MATRIX INVERSION WITH NO SOLUTION

In [8]:
x = np.array([[-4,1],[-4,1]])
x

array([[-4,  1],
       [-4,  1]])

In [9]:
x_inv = np.linalg.inv(x)
x_inv

LinAlgError: Singular matrix