In [2]:
import numpy as np
import torch

In [3]:
A = np.array([[3,4],[5,6],[7,8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [4]:
B = np.array([1,2])
B

array([1, 2])

In [5]:
np.dot(A,B)

array([11, 17, 23])

In [6]:
A_pt = torch.tensor([[3,4],[5,6],[7,8]])
A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [7]:
B_pt = torch.tensor([1,2])
B_pt

tensor([1, 2])

In [8]:
torch.matmul(A_pt, B_pt)

tensor([11, 17, 23])

MATRIX AND MATRIX MULTIPLICATION

In [9]:
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [10]:
B= np.array([[1,9],[2,0]])
B

array([[1, 9],
       [2, 0]])

In [11]:
np.dot(A,B)

array([[11, 27],
       [17, 45],
       [23, 63]])

SYMMTRIC MATRIX

In [12]:
x_sym = np.array([[0,1,2],[1,7,8],[2,8,9]])
x_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [13]:
x_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [14]:
x_sym.T == x_sym    

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [15]:
I = torch.tensor([[1,0,0],[0,1,0],[0,0,1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [16]:
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [17]:
torch.matmul(I, x_pt)

tensor([25,  2,  5])