L2 NORM

In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
(1**2 + 2**2 + 3**2)**(1/2)

3.7416573867739413

In [4]:
np.linalg.norm(x)

3.7416573867739413

L1 NORM

In [5]:
x

array([1, 2, 3])

In [6]:
np.abs(1) + np.abs(2) + np.abs(3)

6

SQUARED L2 NORM

In [7]:
x

array([1, 2, 3])

In [8]:
(1**2 + 2**2 + 3**2)

14

MAX NORM

In [9]:
x

array([1, 2, 3])

In [10]:
np.max([np.abs(1), np.abs(2), np.abs(3)])

3

In [11]:
x = np.array(([1,2],[3,4]))
x

array([[1, 2],
       [3, 4]])

In [12]:
(1**2 + 2**2 + 3**2 + 4**2)**(1/2)

5.477225575051661

In [13]:
np.linalg.norm(x)

5.477225575051661