In [44]:
import numpy as np
import torch

In [45]:
i = np.array([1, 0])
i

array([1, 0])

In [46]:
j = np.array([0, 1])
j

array([0, 1])

In [47]:
np.dot(i, j)

0

MATRICES (RANK 2 TENSORS ) IN NUMPY

In [48]:
x = np.array([[1, 2], [5, 26], [3, 7]])
x

array([[ 1,  2],
       [ 5, 26],
       [ 3,  7]])

In [49]:
x.shape

(3, 2)

In [50]:
x.size

6

In [51]:
#SELECTING AN ENTIRE COLUMN OF MATRIX
x[:,0]

array([1, 5, 3])

In [52]:
#SELECTING A ROW OF MATRIX
x[1, :]

array([ 5, 26])

In [53]:
#SLICING BY INDEX
x[0:2, 0:2]

array([[ 1,  2],
       [ 5, 26]])

In [54]:
images_pt = torch.zeros([32,28,28,3])

ARITHMATIC OPERATIONS WITH TENSORS

In [60]:
x

array([[ 1,  2],
       [ 5, 26],
       [ 3,  7]])

In [64]:
a= x*2
a

array([[ 2,  4],
       [10, 52],
       [ 6, 14]])

In [62]:
x + a

array([[ 3,  6],
       [15, 78],
       [ 9, 21]])

In [63]:
x*a

array([[   2,    8],
       [  50, 1352],
       [  18,   98]])

REDUCTION

In [ ]:
x

In [65]:
x.sum()

44