CREATING A VECTOR

In [28]:
import numpy as np
import torch
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

In [8]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [9]:
len(x)

3

In [10]:
x.shape

(3,)

In [11]:
type(x)

numpy.ndarray

In [12]:
x[0]

1

In [13]:
type(x[0])

numpy.int32

VECTOR TRANSPOSITION

In [14]:
x_trans = x.T
x_trans

array([1, 2, 3])

In [15]:
x_trans.shape

(3,)

In [16]:
y= np.array([[1,2,3]])
y

array([[1, 2, 3]])

In [17]:
y.shape  

(1, 3)

In [18]:
y_trans = y.T
y_trans

array([[1],
       [2],
       [3]])

In [19]:
y_trans.shape

(3, 1)

ZERO VECTORS

In [20]:
z = np.zeros(3)
z

array([0., 0., 0.])

VECTORS IN PyTorch and TensorFlow

In [23]:
x_pt = torch.tensor([1,2,3])
x_pt

tensor([1, 2, 3])

In [24]:
x_tf = tf.Variable([1,2,3])
x_tf

NameError: name 'tf' is not defined